apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-depl.yaml
  - db-svc.yaml
  
configMapGenerator:
  - name: database
    literals:
      - database=books

secretGenerator:
  - name: db-creds
    literals:
      - password=emartdbpass